spring:
  h2:
    console:
      enabled: true
      path: /h2-console

feign:
  client:
    config:
      ipstackClient:
        loggerLevel: full
      openweatherClient:
        loggerLevel: full

logging.level:
  org.assignment.weather.geolocation.IpstackClient: DEBUG
  org.assignment.weather.weather.OpenweatherClient: DEBUG
  org.hibernate.type: TRACE
  feign.Logger: DEBUG